experiment_name: cow/complex/softplus/sparse_views/num_views=10
output_dir: output
seed: 1

dataset: 
  root_dir: ./data/cow_data_40
  img_width: 128
  img_height: 128

model:
  name: nerf
  nb_rays_per_image: 750
  nb_samples_per_ray: 128
  min_depth: 0.1
  n_harmonic_functions: 60
  n_hidden_neurons: 256
  n_hidden_layers: 7
  volume_extent_world: 3
  render_size: 128
  activation: softplus

trainer:
  device: gpu
  num_devices: 1
  max_epochs: 500001
  log_every_n_steps: 10
  log_image_every_n_epochs: 200
  batch_size: 6
  lr: 0.001
  lambda_sil_err: 1.
  lambda_consistency_err: 0.
  lambda_custom_err: 1.

checkpoint:
  save_every_n_epochs: 500
