experiment_name: default
output_dir: output
seed: 1

dataset: 
  root_dir: ./data/170307_dance1/silhouettes

model:
  name: nerf
  nb_rays_per_image: 750
  nb_samples_per_ray: 128
  min_depth: 0.1
  n_harmonic_functions: 60
  n_hidden_neurons: 256
  volume_extent_world: 3
  render_size: 128

trainer:
  device: gpu
  num_devices: 1
  max_epochs: 2000
  log_every_n_steps: 10
  batch_size: 6
  lr: 0.001

checkpoint:
  save_every_n_epochs: 101
